services:
    db:
        image: postgres:14.1
        container_name: infinivista_db
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - local_pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - infinivista_backend
    rabbitmq:
        image: rabbitmq:3.9.13-management
        container_name: infinivista_rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - infinivista_backend
networks:
    infinivista_backend:
        driver: bridge
volumes:
    local_pgdata:
    rabbitmq_data:
