FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install
RUN npm install -g @nestjs/cli

ENV CHOKIDAR_USEPOLLING=true
ENV NODE_ENV=development

CMD ["npm", "run", "start:dev", "--", "--watch", "--poll=1000"]