INSERT INTO topic (id, "topicName", "topicDescription", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Technology', 'Discussions about the latest tech innovations, gadgets, programming, AI, and digital trends', NOW(), NOW()),
(gen_random_uuid(), 'Travel', 'Explore destinations, travel tips, adventures, cultural experiences, and global journeys', NOW(), NOW()),
(gen_random_uuid(), 'Food & Cooking', 'Recipe sharing, culinary techniques, restaurant reviews, and food photography', NOW(), NOW()),
(gen_random_uuid(), 'Health & Fitness', 'Workout routines, nutrition advice, mental wellbeing, and healthy lifestyle tips', NOW(), NOW()),
(gen_random_uuid(), 'Art & Design', 'Creative works, design principles, visual arts, digital creations, and artistic inspiration', NOW(), NOW()),
(gen_random_uuid(), 'Books & Literature', 'Book recommendations, literary discussions, author spotlights, and reading challenges', NOW(), NOW()),
(gen_random_uuid(), 'Photography', 'Photography techniques, equipment reviews, photo editing tips, and visual storytelling', NOW(), NOW()),
(gen_random_uuid(), 'Music', 'Music reviews, artist discussions, instrument learning, and musical appreciation', NOW(), NOW()),
(gen_random_uuid(), 'Fashion', 'Style trends, outfit ideas, fashion industry news, and clothing recommendations', NOW(), NOW()),
(gen_random_uuid(), 'Environment', 'Environmental issues, sustainability practices, conservation efforts, and eco-friendly living', NOW(), NOW()),
(gen_random_uuid(), 'Gaming', 'Video game discussions, gaming news, strategies, reviews, and esports', NOW(), NOW()),
(gen_random_uuid(), 'Sports', 'Sports news, team updates, game analysis, athletic achievements, and fitness competitions', NOW(), NOW()),
(gen_random_uuid(), 'Science', 'Scientific discoveries, research breakthroughs, space exploration, and academic discussions', NOW(), NOW()),
(gen_random_uuid(), 'Education', 'Learning resources, teaching methods, academic support, and educational technology', NOW(), NOW()),
(gen_random_uuid(), 'Personal Finance', 'Investment tips, budgeting strategies, financial planning, and economic insights', NOW(), NOW()),
(gen_random_uuid(), 'Parenting', 'Child-rearing advice, family activities, educational resources, and parenting support', NOW(), NOW()),
(gen_random_uuid(), 'DIY & Crafts', 'Handmade projects, crafting tutorials, upcycling ideas, and creative home solutions', NOW(), NOW()),
(gen_random_uuid(), 'Politics', 'Political news, policy discussions, governance issues, and civic engagement', NOW(), NOW()),
(gen_random_uuid(), 'History', 'Historical events, archaeological findings, ancient civilizations, and cultural heritage', NOW(), NOW()),
(gen_random_uuid(), 'Movies & TV', 'Film reviews, TV show discussions, streaming recommendations, and entertainment news', NOW(), NOW()),
(gen_random_uuid(), 'Pets & Animals', 'Pet care tips, animal facts, wildlife conservation, and veterinary advice', NOW(), NOW()),
(gen_random_uuid(), 'Mental Health', 'Psychological wellbeing, therapy insights, mindfulness practices, and emotional support', NOW(), NOW()),
(gen_random_uuid(), 'Career Development', 'Professional growth tips, job search strategies, workplace skills, and industry trends', NOW(), NOW()),
(gen_random_uuid(), 'Home Decor', 'Interior design ideas, home styling tips, decoration trends, and space organization', NOW(), NOW()),
(gen_random_uuid(), 'Relationships', 'Dating advice, partnership insights, communication skills, and social connections', NOW(), NOW()),
(gen_random_uuid(), 'Gardening', 'Plant care guides, landscaping ideas, urban gardening, and botanical knowledge', NOW(), NOW()),
(gen_random_uuid(), 'Automotive', 'Car reviews, maintenance tips, automotive technology, and vehicle customization', NOW(), NOW()),
(gen_random_uuid(), 'Comedy & Humor', 'Jokes, funny stories, comedy performances, and humorous content creation', NOW(), NOW()),
(gen_random_uuid(), 'Spirituality', 'Spiritual practices, mindfulness, philosophical discussions, and personal growth', NOW(), NOW()),
(gen_random_uuid(), 'Cultural Heritage', 'Traditional customs, historical preservation, cultural celebrations, and ethnic identity', NOW(), NOW()),
(gen_random_uuid(), 'Cryptocurrency', 'Blockchain technologies, digital currencies, trading strategies, and crypto market analysis', NOW(), NOW()),
(gen_random_uuid(), 'Artificial Intelligence', 'Machine learning advancements, AI ethics, neural networks, and practical applications', NOW(), NOW()),
(gen_random_uuid(), 'Space Exploration', 'Astronomy discoveries, space missions, planetary science, and cosmic phenomena', NOW(), NOW()),
(gen_random_uuid(), 'Virtual Reality', 'VR hardware, immersive experiences, development techniques, and future applications', NOW(), NOW()),
(gen_random_uuid(), 'Sustainable Living', 'Zero-waste lifestyle, eco-friendly products, sustainability practices, and green innovations', NOW(), NOW()),
(gen_random_uuid(), 'Remote Work', 'Work-from-home tips, digital nomad lifestyle, remote collaboration, and virtual productivity', NOW(), NOW()),
(gen_random_uuid(), 'Coffee Culture', 'Brewing techniques, bean varieties, café reviews, equipment recommendations, and coffee history', NOW(), NOW()),
(gen_random_uuid(), 'Language Learning', 'Learning methods, language exchange, linguistic insights, and multilingual resources', NOW(), NOW()),
(gen_random_uuid(), 'Running', 'Training plans, running gear, race events, marathon preparation, and jogging techniques', NOW(), NOW()),
(gen_random_uuid(), 'Yoga & Meditation', 'Yoga poses, meditation practices, mindfulness techniques, and spiritual wellness', NOW(), NOW()),
(gen_random_uuid(), 'Cycling', 'Bike maintenance, cycling routes, equipment reviews, racing news, and urban biking', NOW(), NOW()),
(gen_random_uuid(), 'Astronomy', 'Stargazing guides, celestial events, telescope tips, and planetary information', NOW(), NOW()),
(gen_random_uuid(), 'Hiking & Backpacking', 'Trail recommendations, outdoor gear, wilderness skills, and hiking adventures', NOW(), NOW()),
(gen_random_uuid(), 'Web Development', 'Coding tutorials, web design trends, development frameworks, and programming resources', NOW(), NOW()),
(gen_random_uuid(), 'Graphic Design', 'Design principles, visual aesthetics, software tutorials, and creative inspirations', NOW(), NOW()),
(gen_random_uuid(), 'Cybersecurity', 'Online safety, security practices, threat prevention, and privacy protection', NOW(), NOW()),
(gen_random_uuid(), 'Urban Planning', 'City development, architecture trends, public spaces, and community design', NOW(), NOW()),
(gen_random_uuid(), 'Board Games', 'Game reviews, strategy discussions, new releases, and gaming community events', NOW(), NOW()),
(gen_random_uuid(), 'Podcasting', 'Show recommendations, production tips, industry trends, and podcasting equipment', NOW(), NOW()),
(gen_random_uuid(), 'Knitting & Crochet', 'Pattern sharing, yarn reviews, technique tutorials, and fiber arts community', NOW(), NOW()),
(gen_random_uuid(), 'Mythology', 'Ancient stories, folklore traditions, mythological creatures, and cultural legends', NOW(), NOW()),
(gen_random_uuid(), 'Street Art', 'Urban art movements, graffiti culture, mural projects, and street artists', NOW(), NOW()),
(gen_random_uuid(), 'Martial Arts', 'Fighting techniques, training methods, philosophical aspects, and competition news', NOW(), NOW()),
(gen_random_uuid(), 'Vintage Collecting', 'Antique finds, collectible markets, restoration tips, and historical items', NOW(), NOW()),
(gen_random_uuid(), 'Volunteering', 'Community service opportunities, nonprofit work, social impact, and charitable initiatives', NOW(), NOW()),
(gen_random_uuid(), 'Minimalism', 'Simple living philosophy, decluttering methods, mindful consumption, and space optimization', NOW(), NOW()),
(gen_random_uuid(), 'Blockchain', 'Distributed ledger technology, smart contracts, blockchain applications, and decentralized systems', NOW(), NOW()),
(gen_random_uuid(), 'Beekeeping', 'Honey production, bee conservation, hive management, and pollinator protection', NOW(), NOW()),
(gen_random_uuid(), 'Vegetarianism & Veganism', 'Plant-based recipes, ethical eating, sustainable food choices, and nutritional advice', NOW(), NOW()),
(gen_random_uuid(), 'Architecture', 'Building design, architectural styles, innovative structures, and urban landscapes', NOW(), NOW()),
(gen_random_uuid(), 'Dance', 'Dance styles, performance art, choreography techniques, and movement expression', NOW(), NOW()),
(gen_random_uuid(), 'Fishing', 'Angling techniques, fishing spots, equipment reviews, and aquatic conservation', NOW(), NOW()),
(gen_random_uuid(), 'Astronomy Photography', 'Night sky photography, astrophotography equipment, celestial imaging, and space photography', NOW(), NOW()),
(gen_random_uuid(), 'Sewing', 'Sewing patterns, fabric selection, machine reviews, and clothing construction', NOW(), NOW()),
(gen_random_uuid(), 'Calligraphy', 'Handwriting styles, lettering techniques, penmanship improvement, and script art', NOW(), NOW()),
(gen_random_uuid(), 'Mechanical Keyboards', 'Keyboard builds, switch types, keycap collections, and typing enthusiasts', NOW(), NOW()),
(gen_random_uuid(), 'Jazz', 'Jazz history, influential musicians, album reviews, and musical improvisation', NOW(), NOW()),
(gen_random_uuid(), 'Wine Appreciation', 'Wine tasting, vineyard reviews, vintage information, and food pairings', NOW(), NOW()),
(gen_random_uuid(), 'Fermentation', 'Fermenting techniques, probiotics, home brewing, and traditional preservation methods', NOW(), NOW()),
(gen_random_uuid(), 'Indoor Plants', 'Houseplant care, species identification, propagation methods, and botanical displays', NOW(), NOW()),
(gen_random_uuid(), 'Soap Making', 'DIY soap recipes, cold process methods, ingredient selection, and creative designs', NOW(), NOW()),
(gen_random_uuid(), 'Origami', 'Paper folding techniques, origami models, artistic creations, and geometric designs', NOW(), NOW()),
(gen_random_uuid(), 'Physics', 'Scientific principles, theoretical concepts, physics experiments, and scientific breakthroughs', NOW(), NOW()),
(gen_random_uuid(), 'Ceramics', 'Pottery techniques, ceramic art, firing methods, and clay crafting', NOW(), NOW()),
(gen_random_uuid(), 'Classical Music', 'Composers, orchestras, musical analysis, concerts, and classical recordings', NOW(), NOW()),
(gen_random_uuid(), 'Entrepreneurship', 'Startup advice, business development, innovation strategies, and founder stories', NOW(), NOW()),
(gen_random_uuid(), 'Woodworking', 'Carpentry skills, furniture making, wood carving, and workshop projects', NOW(), NOW()),
(gen_random_uuid(), 'Camping', 'Outdoor adventures, camping gear, wilderness tips, and nature exploration', NOW(), NOW()),
(gen_random_uuid(), 'Baking', 'Bread making, pastry techniques, dessert recipes, and baking science', NOW(), NOW()),
(gen_random_uuid(), 'Chess', 'Strategy discussions, famous matches, playing techniques, and chess theory', NOW(), NOW()),
(gen_random_uuid(), 'Makeup Artistry', 'Cosmetic techniques, product reviews, beauty trends, and creative looks', NOW(), NOW()),
(gen_random_uuid(), 'Watches', 'Timepiece collections, watchmaking craftsmanship, vintage models, and horological appreciation', NOW(), NOW()),
(gen_random_uuid(), 'Blockchain Gaming', 'Play-to-earn games, NFT collectibles, virtual economies, and blockchain game development', NOW(), NOW()),
(gen_random_uuid(), 'Drumming', 'Percussion techniques, rhythm discussions, drum gear, and musical practice', NOW(), NOW()),
(gen_random_uuid(), 'Basketball', 'Game analysis, player achievements, basketball skills, and league discussions', NOW(), NOW()),
(gen_random_uuid(), 'Soccer/Football', 'Match reviews, team news, football tactics, player transfers, and fan culture', NOW(), NOW()),
(gen_random_uuid(), 'Tennis', 'Tournament coverage, player techniques, tennis equipment, and match analysis', NOW(), NOW()),
(gen_random_uuid(), 'Golf', 'Course reviews, swing techniques, equipment recommendations, and tournament news', NOW(), NOW()),
(gen_random_uuid(), 'Skiing & Snowboarding', 'Winter sports techniques, resort reviews, equipment guides, and snow conditions', NOW(), NOW()),
(gen_random_uuid(), 'Surfing', 'Wave riding techniques, surf spots, board selection, and ocean knowledge', NOW(), NOW()),
(gen_random_uuid(), 'Rock Climbing', 'Climbing techniques, outdoor routes, indoor training, and equipment reviews', NOW(), NOW()),
(gen_random_uuid(), 'Painting', 'Artistic techniques, medium discussions, art history, and creative expression', NOW(), NOW()),
(gen_random_uuid(), 'Sculpture', '3D art forms, sculptural techniques, material exploration, and dimensional creativity', NOW(), NOW()),
(gen_random_uuid(), 'Bird Watching', 'Species identification, wildlife observation, birding locations, and avian conservation', NOW(), NOW()),
(gen_random_uuid(), 'Stand-up Comedy', 'Performance techniques, comedian spotlights, open mic venues, and humor analysis', NOW(), NOW()),
(gen_random_uuid(), 'Mindfulness', 'Present-moment awareness, meditation techniques, attentional training, and stress reduction', NOW(), NOW()),
(gen_random_uuid(), 'Botany', 'Plant science, species classification, botanical research, and floral diversity', NOW(), NOW());
